services:
  application:
    build:
      context: application
      dockerfile: Dockerfile
    container_name: Application
    depends_on:
      - postgres
      - mysql
      - mongodb
      - dynamodb
    environment:
      - DATABASE=${DATABASE}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
    networks:
      - internal-network

  postgres:
    image: postgres:latest
    container_name: PostgreSQL
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - ${POSTGRES_OUTER_PORT}:${POSTGRES_INNER_PORT}
    volumes:
      - ./init/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
    networks:
      - internal-network

  mysql:
    image: mysql:latest
    container_name: MySQL
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - ${MYSQL_OUTER_PORT}:${MYSQL_INNER_PORT}
    volumes:
      - ./init/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    networks:
      - internal-network

  mongodb:
    image: mongo:latest
    container_name: MongoDB
    command: mongod --bind_ip_all
    ports:
      - ${MONGO_OUTER_PORT}:${MONGO_INNER_PORT}
    volumes:
      - ./init/mongo.js:/docker-entrypoint-initdb.d/mongo.js
    networks:
      - internal-network

  dynamodb:
    image: amazon/dynamodb-local
    container_name: DynamoDB
    command: "-jar DynamoDBLocal.jar -sharedDb"
    ports:
      - ${DYNAMO_OUTER_PORT}:${DYNAMO_INNER_PORT}
    networks:
      - internal-network

  dynamodb-initializer:
    image: python:slim
    container_name: DynamoDB_Initializer
    depends_on:
      - dynamodb
    volumes:
      - ./init/dynamo.py:/docker-entrypoint-initdb.d/dynamo.py
    working_dir: /docker-entrypoint-initdb.d
    command: [ "sh", "-c", "pip install boto3 && python dynamo.py" ]
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
